imports:
    - { resource: config.yml }

parameters:
    app.config:
        title: "ISIN Analytics [beta]"
        allowAdverts: false

security:
    firewalls:
        default:
            anonymous: false
            http_basic: ~