imports:
    - { resource: config_dev.yml }

parameters:
    app.config:
        title: "ISIN Analytics [alpha]"
        allowAdverts: false

security:
    firewalls:
        default:
            anonymous: ~
            http_basic: ~