security:
    providers:
        app_user_provider:
            id: app.security.user_provider
#        in_memory:
#            memory:
#                users:
#                    admin:
#                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

    access_control:
        - { path: ^/(login|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#
#        login_firewall:
#            pattern:   ^/(login|reset-password|first-user)$
#            anonymous: ~
#
#        secured_area:
#            pattern:    ^/admin
#            form_login:
#                login_path: login
#                check_path: login_check
#                provider: app_user_provider
#            logout:
#                path:   logout
#                target: home
##            remember_me:
##                key:      "%secret%"
##                lifetime: 9.46708e8 # 30 years
##                path:     /
##                always_remember_me: true
#
#        default:
#            anonymous: ~
#
#    access_control:
#        - { path: ^/admin, roles: [ROLE_ADMIN] }
#        - { path: ^/, roles: [ROLE_ADMIN, IS_AUTHENTICATED_ANONYMOUSLY] }

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        AppBundle\Security\Visitor:
            id: app.security.encoder