home:
  path:     /
  defaults: { _controller: AppBundle:Home:index }

styleguide:
  path:     /styleguide
  defaults: { _controller: AppBundle:Home:styleguide }

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

reset_password:
    path:     /reset-password
    defaults: { _controller: AppBundle:Security:resetPassword }

reset_password:
    path:     /set-password
    defaults: { _controller: AppBundle:Security:setPassword }

login_check:
    path: /login-check

logout:
    path: /logout

users_list:
  path:     /users
  defaults: { _controller: AppBundle:Users:list }

users_new:
  path:     /users/new
  defaults: { _controller: AppBundle:Users:new }

users_show:
  path:     /users/{user_key}
  defaults: { _controller: AppBundle:Users:show }

users_first:
  path:     /first-user
  defaults: { _controller: AppBundle:Users:firstUser }