home:
  path:     /
  defaults: { _controller: AppBundle:Home:index }

styleguide:
  path:     /styleguide
  defaults: { _controller: AppBundle:Home:styleguide }

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

securities_list:
  path:     /securities
  defaults: { _controller: AppBundle:Securities:list }

securities_show:
  path:     /securities/{isin}
  defaults: { _controller: AppBundle:Securities:show }
