home:
  path:     /
  defaults: { _controller: AppBundle:Home:index }

sitemap:
  path:     /sitemap.xml
  defaults: { _controller: AppBundle:Home:sitemap }

styleguide:
  path:     /styleguide
  defaults: { _controller: AppBundle:Home:styleguide }

about:
  path:     /about
  defaults: { _controller: AppBundle:Home:about }

terms:
  path:     /terms
  defaults: { _controller: AppBundle:Home:terms }

privacy_policy:
  path:     /privacy-policy
  defaults: { _controller: AppBundle:Home:privacy }

search:
  path:     /search.{format}
  defaults: { _controller: AppBundle:Search:list, format: null }

# Admin
admin:
  path:     /admin
  defaults: { _controller: AppBundle:Admin:index }

admin_securities:
  path:     /admin/securities
  defaults: { _controller: AppBundle:Admin:securities }

admin_process_security:
  path:     /admin/process-security.json
  defaults: { _controller: AppBundle:Admin:processSecurity, format: json }

admin_issuers:
  path:     /admin/issuers
  defaults: { _controller: AppBundle:Admin:issuers }

admin_process_issuers:
  path:     /admin/process-issuer.json
  defaults: { _controller: AppBundle:Admin:processIssuer, format: json }

# Overview
overview:
  path:     /overview
  defaults: { _controller: AppBundle:Overview:show }

# @todo - Overview - issuance, maturity-profile, yield curves, etc

# Securities
security_list:
  path:     /securities
  defaults: { _controller: AppBundle:Securities:list }

security_show:
  path:     /securities/{isin}.{format}
  defaults: { _controller: AppBundle:Securities:show, format: null }
  requirements:
    isin:  "[A-Za-z0-9]{12}" # catching lowercase here, so we can redirect it to uppercase

# Issuers
issuer_list:
  path:     /issuers
  defaults: { _controller: AppBundle:Issuers:list }

issuer_show:
  path:     /issuers/{issuer_id}.{format}
  defaults: { _controller: AppBundle:Issuers:show, format: null }

issuer_securities:
  path:     /issuers/{issuer_id}/securities
  defaults: { _controller: AppBundle:Issuers:securities }


issuer_maturity_profile:
  path:     /issuers/{issuer_id}/maturity-profile
  defaults: { _controller: AppBundle:Issuers:maturityProfile }

issuer_issuance:
  path:     /issuers/{issuer_id}/issuance/{year}
  defaults: { _controller: AppBundle:Issuers:issuance, year: null }

# Groups
group_list:
  path:     /groups
  defaults: { _controller: AppBundle:Groups:list }

group_show:
  path:     /groups/{group_id}
  defaults: { _controller: AppBundle:Groups:show }

group_issuance:
  path:     /groups/{group_id}/issuance/{year}
  defaults: { _controller: AppBundle:Groups:issuance, year: null }

group_securities:
  path:     /groups/{group_id}/securities
  defaults: { _controller: AppBundle:Groups:securities }

group_maturity_profile:
  path:     /groups/{group_id}/maturity-profile
  defaults: { _controller: AppBundle:Groups:maturityProfile }

group_yield:
  path:     /groups/{group_id}/yield
  defaults: { _controller: AppBundle:Groups:yield }


# Industries
industry_list:
  path:     /industries
  defaults: { _controller: AppBundle:Industries:list }

industry_show:
  path:     /industries/{industry_id}
  defaults: { _controller: AppBundle:Industries:show }

industry_securities:
  path:     /industries/{industry_id}/securities
  defaults: { _controller: AppBundle:Industries:securities }

industry_maturity_profile:
  path:     /industries/{industry_id}/maturity-profile
  defaults: { _controller: AppBundle:Industries:maturityProfile }

industry_issuance:
  path:     /industries/{industry_id}/issuance/{year}
  defaults: { _controller: AppBundle:Industries:issuance, year: null }

# Sectors
sector_list:
  path:     /sectors
  defaults: { _controller: AppBundle:Sectors:list }

sector_show:
  path:     /sectors/{sector_id}
  defaults: { _controller: AppBundle:Sectors:show }

sector_securities:
  path:     /sectors/{sector_id}/securities
  defaults: { _controller: AppBundle:Sectors:securities }

sector_maturity_profile:
  path:     /sectors/{sector_id}/maturity-profile
  defaults: { _controller: AppBundle:Sectors:maturityProfile }

sector_issuance:
  path:     /sectors/{sector_id}/issuance/{year}
  defaults: { _controller: AppBundle:Sectors:issuance, year: null }

# Reports
report_list:
  path:     /reports
  defaults: { _controller: AppBundle:Reports:list }

report_fsa54:
  path:     /reports/fsa54
  defaults: { _controller: AppBundle:Reports:fsa54 }

report_fsa50:
  path:     /reports/fsa50
  defaults: { _controller: AppBundle:Reports:fsa50 }