home:
  path:     /
  defaults: { _controller: AppBundle:Home:index }

styleguide:
  path:     /styleguide
  defaults: { _controller: AppBundle:Home:styleguide }

about:
  path:     /about
  defaults: { _controller: AppBundle:Home:about }

search:
  path:     /search
  defaults: { _controller: AppBundle:Search:list }

securities_list:
  path:     /securities
  defaults: { _controller: AppBundle:Securities:list }

securities_show:
  path:     /securities/{isin}
  defaults: { _controller: AppBundle:Securities:show }
  requirements:
    isin:  "[A-Z0-9]{12}"


issuers_list:
  path:     /issuers
  defaults: { _controller: AppBundle:Issuers:list }

issuers_show:
  path:     /issuers/{issuer_id}
  defaults: { _controller: AppBundle:Issuers:show }

issuers_securities:
  path:     /issuers/{issuer_id}/securities/{line_id}
  defaults: { _controller: AppBundle:Issuers:securities, line_id: null }


issuers_maturity_profile:
  path:     /issuers/{issuer_id}/maturity-profile
  defaults: { _controller: AppBundle:Issuers:maturityProfile, year: null }

issuers_issuance:
  path:     /issuers/{issuer_id}/issuance/{year}
  defaults: { _controller: AppBundle:Issuers:issuance, year: null }
