services:

  app.listener.preexecute:
      class: AppBundle\Resources\Listener
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  app.services.issuers:
      class: SecuritiesService\Service\IssuersService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.lines:
      class: SecuritiesService\Service\LinesService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.securities:
      class: SecuritiesService\Service\SecuritiesService
      arguments: ["@doctrine.orm.default_entity_manager"]
