services:

  app.listener.preexecute:
      class: AppBundle\Resources\Listener
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  app.twig_extension:
        class: AppBundle\Extension\AssetPathExtension
        public: false
        arguments: ["%kernel.root_dir%/config"]
        tags:
            - { name: twig.extension }

  app.guzzle_client:
      class: GuzzleHttp\Client

  app.data_services.drive:
      class: DataService\Service\DriveService
      arguments: ["@app.guzzle_client","%google_api_key%","%google_source_email%"]

  app.services.buckets:
      class: SecuritiesService\Service\BucketsService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.currencies:
      class: SecuritiesService\Service\CurrenciesService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.groups:
      class: SecuritiesService\Service\GroupsService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.industries:
      class: SecuritiesService\Service\IndustriesService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.issuers:
      class: SecuritiesService\Service\IssuersService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.products:
      class: SecuritiesService\Service\ProductsService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.securities:
      class: SecuritiesService\Service\SecuritiesService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.securities_by_group:
      class: SecuritiesService\Service\Securities\ByGroupService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.securities_by_industry:
      class: SecuritiesService\Service\Securities\ByIndustryService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.securities_by_issuer:
      class: SecuritiesService\Service\Securities\ByIssuerService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.securities_by_sector:
      class: SecuritiesService\Service\Securities\BySectorService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.securities_search:
      class: SecuritiesService\Service\Securities\SearchService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.sectors:
      class: SecuritiesService\Service\SectorsService
      arguments: ["@doctrine.orm.default_entity_manager"]

  app.services.yields:
      class: SecuritiesService\Service\YieldCurvesService
      arguments: ["@doctrine.orm.default_entity_manager"]
