services:

  app.listener.preexecute:
      class: AppBundle\Resources\Listener
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  app.security.encoder:
      class: AppBundle\Security\Encoder

  app.security.user_provider:
      class: AppBundle\Security\UserProvider
      arguments: [@app.services.users]

  app.services.email:
      class: AppBundle\Service\EmailService
      arguments: [@swiftmailer.mailer, %mailer_user%]

  app.services.settings:
      class: AppBundle\Service\SettingsService
      arguments: [@database.services.query_factory]

  app.services.users:
      class: AppBundle\Service\UsersService
      arguments: [@database.services.query_factory]
