services:

  app.listener.preexecute:
      class: AppBundle\Resources\Listener
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  app.twig_extension:
      class: AppBundle\Extension\AssetPathExtension
      public: false
      arguments: ["%kernel.root_dir%/config"]
      tags:
          - { name: twig.extension }

  app.time_provider:
      class: DateTimeImmutable

  app.bucket_provider:
      class: SecuritiesService\Data\BucketProvider
      arguments: ["@app.time_provider"]

  app.security.encoder:
      class: AppBundle\Security\Encoder

  app.security.user_provider:
      class: AppBundle\Security\UserProvider
      arguments: ["@app.services.users"]

  app.config:
      class: SecuritiesService\Domain\Entity\Config
      factory: ["@app.services.config", get]

  app.email.from_name:
      class: SecuritiesService\Domain\Entity\Config
      factory: ["@app.config", getSiteTitle]


  app.email.sender:
      class: AppBundle\Service\EmailService
      arguments:
          - "@swiftmailer.mailer"
          - %mailer_user%
          - "@app.email.from_name"


  app.services.buckets:
      class: SecuritiesService\Service\BucketsService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.currencies:
      class: SecuritiesService\Service\CurrenciesService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.countries:
      class: SecuritiesService\Service\CountriesService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.config:
      class: SecuritiesService\Service\ConfigService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.exchange_rates:
      class: SecuritiesService\Service\ExchangeRatesService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.groups:
      class: SecuritiesService\Service\GroupsService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.industries:
      class: SecuritiesService\Service\IndustriesService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.issuers:
      class: SecuritiesService\Service\IssuersService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.products:
      class: SecuritiesService\Service\ProductsService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.securities:
      class: SecuritiesService\Service\SecuritiesService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.securities_by_group:
      class: SecuritiesService\Service\Securities\ByGroupService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.securities_by_industry:
      class: SecuritiesService\Service\Securities\ByIndustryService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.securities_by_issuer:
      class: SecuritiesService\Service\Securities\ByIssuerService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.securities_by_sector:
      class: SecuritiesService\Service\Securities\BySectorService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.securities_search:
      class: SecuritiesService\Service\Securities\SearchService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.sectors:
      class: SecuritiesService\Service\SectorsService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.users:
      class: SecuritiesService\Service\UsersService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"

  app.services.yields:
      class: SecuritiesService\Service\YieldCurvesService
      arguments:
          - "@doctrine.orm.default_entity_manager"
          - "@app.bucket_provider"
          - "@app.time_provider"
