services:

  app.listener.preexecute:
      class: AppBundle\Resources\Listener
      tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  app.services.securities:
      class: AppBundle\Service\SecuritiesService
      arguments: [@database.services.query_factory]
